name = "ppk-canteen"
compatibility_date = "2024-09-23"
pages_build_output_dir = "frontend"

[[d1_databases]]
binding = "DB"
database_name = "ppk-canteen-db"
database_id = "7ec61ad1-3718-401d-9697-193e112b718b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "ppk-canteen-files"

[ai]
binding = "AI"

# Secrets (ตั้งค่าผ่าน wrangler secret put):
# JWT_SECRET — สำหรับ sign/verify JWT token
